name: build docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
     
          node-version: 18.x
          check-latest: true
          cache: npm
          cache-dependency-path: /home/ubuntu/docker/_work/fullstack-app/fullstack-app/package-lock.json
      - run: npm ci
      - run: npm test
      - run: sudo npm install -y
      - run: sudo npm start 
      - run: sudp npm run build
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: >-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
             hashFiles('**/package-lock.json') }}
               restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-project
          path: build
          retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Download build for testing
        uses: actions/download-artifact@v3
        with:
          name: built-project
      - run: sudo npm install -y
      - run: sudo npm run pipeline-test
  run-name:
    needs: [build, test]
    name: deploy to docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with-ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
