name: build docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Uso Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          check-latest: true
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install package dependencias
        run: sudo npm install -y
      - name: Instaclación de docker
        run: sudo apt install ca-certificates curl gnupg lsb-release -y | sudo mkdir -p /etc/apt/keyrings
      - name: validación
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg | sudo chmod a+r /etc/apt/keyrings/docker.gpg
      - name: Añadir paquetes
        run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - name: acutalización Ubuntu
        run: sudo apt update
      - name: instalar paquete de somponenetes de docker
        run: sudo apt install docker-ce docker-ce-cli containerd.io -y

      # - name: Construción de la imagen de docker
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
