name: build docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          check-latest: true
      - name: Checkout to the repository
        uses: actions/checkout@v2
        
#       - name: Set up NodeJS environment
#         uses: actions/setup-node@v2
#         with:
#           # Reads the node version from the .nvmrc file itself 
#           node-version-file: '.nvmrc'
#           # The node version can be hard-coded 
#           # node-version: 14
        
      # Consider this as an add on to optimize the execution of actions
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
       
      - name: Install package dependencies
        run: npm install
      
      - name: Check linting and formatting
        # Custom script for checking the linting and formatting being in place
        run: sudo npm run lint
      
      # Run test cases and this could ensure minimum coverage as well if set
      - name: Execute test cases
        run: npm run test
        
      - name: Create test build
        run: npm run build
      - run: npm init -y
      - run: sudo npm install -y
      - run: sudo apt install docker.io -y
      - run: sudo apt install docker-compose -y
      - run: sudo docker-compose --version
      - run: sudo docker-compose up
      - name: Checkout
        uses: actions/checkout@v3
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
     
      
#      - run: sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin  
      - run: docker-compose up -d
      - run: docker-compose ps
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: >-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
             hashFiles('**/package-lock.json') }}
               restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-project
          path: build
          retention-days: 1
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with-ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: user/app:latest
#   run-name:
#     needs: build
#     name: deploy to docker
#     runs-on: self-hosted
#     steps:     
#       - uses: actions/checkout@master
#       - uses: docker/build-push-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           tag_with-ref: true
#           tag_with_sha: true
#           tags: ${{ github.sha }}
