name: build docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Uso Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          check-latest: true
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install package dependencias
        run: sudo npm install -y
     
# run-name:
#   needs: build
#   name: deploy to docker
#   runs-on: self-hosted
#   steps:
#     - uses: actions/checkout@master
#     - uses: docker/build-push-action@v1
#     with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           tag_with-ref: true
#           tag_with_sha: true
#           tags: ${{ github.sha }}
